export const HYDRATE = "HYDRATE";
export const AUTHENTICATE = "AUTHENTICATE";
export const AUTHENTICATE_ERROR = "AUTHENTICATE_ERROR";
export const DEAUTHENTICATE = "DEAUTHENTICATE";

export const MANAGER_GET_FREEZER = "MANAGER_GET_FREEZER";
export const MANAGER_GET_FREEZER_ERROR = "MANAGER_GET_FREEZER_ERROR";
export const MANAGER_GET_STAFF = "MANAGER_GET_STAFF";
export const MANAGER_GET_FREEZER_HISTORY = "MANAGER_GET_FREEZER_HISTORY";
export const REMOVE_MANAGER = "REMOVE_MANAGER";

export const SET_SHARE_TO_STAFF = "SET_SHARE_TO_STAFF";
export const SHARE_TO_STAFF = "SUBMIT_SHARE_TO_STAFF";

export const SET_SHARE_TO_GROUP = "SET_SHARE_TO_GROUP";
export const SHARE_TO_GROUP = "SHARE_TO_GROUP";